### ISSUE TITLE
Autocomplete fails to account for removed tags

### ISSUE THREAD

**Issue by cannahum** [cannahum/DressCodeIONIC#1]
items-removed-method="autoCompleteStuff.removedMethod(callback)" is not working

ion-autocomplete takes in a directive called "items-removed-method". This calls a method inside the controller called "removedMethod". Rather, it should, but it isn't.

Any ideas?

**Comment by cannahum** [comment]
Ryan, I just assigned you to try out ISSUES. you don't need to look if you don't want to.

**Comment by RyanMarcus** [comment]
I'm not sure if you are talking about the profile section or the model section -- 

It looks liked you are properly injecting in `profile.js`:


    var profileController = angular.module('starter.profile', ['ngTagsInput'])
    .controller('ProfileCtrl', function($scope) {
  
    });


... but not in `model.js`:

```javascript
var modelController = angular.module('starter.model', [])

.controller('ModelCtrl', function($scope, $http) {

	$scope.tags = [];
	$scope.loadTags = function(query) {
		return $http.get('/www/lib/tags.json');
	};
  
});
```

Further, I think you need a different query function. You have this line in `model.html`:

```html
 <auto-complete source="loadTags($query)"></auto-complete>
```

... which tells `auto-complete` to use the `loadTags` function as a query function. According to the documentation [here](http://mbenford.github.io/ngTagsInput/gettingstarted), such a query function should...

> You should pass a function of the scope to the source attribute. That function will be called for every keystroke (not quite on every keystroke, since there's a debounce delay) on the input field and will be provided with its current value (through the $query argument). That function also must return either an array of objects or a promise which eventually resolves to either an array of objects or an object with a data property containing an array of objects (e.g. $http promises).

Your current implementation just gives back the same taglist (after fetching it from the server!!) every time:

```javascript
$scope.loadTags = function(query) {
		return $http.get('/www/lib/tags.json');
};
```

I'm sure you are just testing, but you might wanna change that. Especially the injection issue -- could be causing your other problem.

As for `items-removed-method` specifically, I [can't find any use of it in the repo, so I'm not sure what isn't working](https://github.com/cannahum/DressCodeIONIC/search?utf8=%E2%9C%93&q=items-removed-method).

My understand is that, when a tag is removed, the model is automatically updated. See `Basic Usage` on the page linked above.

**Comment by cannahum** [comment]
Hey Ryan,

thanks for the response. You looked at the master, whereas I was working on a different branch. But your comments on dependency injection and server requests were transferable to my issue. Now it's solved.

thanks!

**Comment by RyanMarcus** [comment]
Ah, gotcha! Glad you figured it out.

Let me know if there's a specific branch you want me to look at.
